### ISSUE TITLE
feat(p2p): implement station-to-station protocol

### ISSUE THREAD

**Issue by nonvis** [NoirHQ/smite#151]
In order to prevent man-in-the-middle attack, encrypt all connection channels between two peers.

- implement station-to-station protocol using X25519 keys for Diffie-Helman key-exchange and chacha20poly1305 for encryption

**Comment by conr2d** [comment]
Which library do you plan to use for this?

**Comment by nonvis** [comment]
I was thinking of using libsodium for encrypting stream using chacha20poly1305 but also use crypto++ if some functionalities are not available in libsodium. For example, hkdf-sha2 is required to generate the secret used for receiving and sending but it's not available in libsodium.

**Comment by conr2d** [comment]
It seems that openssl also provides hkdf-sha2. [[link]](https://www.openssl.org/docs/manmaster/man7/EVP_KDF-HKDF.html)
I agree with you about adding libsodium dependency.

**Comment by nonvis** [comment]
closed this in #187
